/*
 * This file is generated by jOOQ.
*/
package com.st.nicobot.db;


import com.st.nicobot.db.tables.Gommette;
import com.st.nicobot.db.tables.Greeter;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -408134082;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.GREETER</code>.
     */
    public final Greeter GREETER = com.st.nicobot.db.tables.Greeter.GREETER;

    /**
     * The table <code>PUBLIC.GOMMETTE</code>.
     */
    public final Gommette GOMMETTE = com.st.nicobot.db.tables.Gommette.GOMMETTE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Greeter.GREETER,
            Gommette.GOMMETTE);
    }
}
