/*
 * This file is generated by jOOQ.
*/
package com.st.nicobot.db;


import com.st.nicobot.db.tables.Gommette;
import com.st.nicobot.db.tables.Greeter;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.GREETER</code>.
     */
    public static final Greeter GREETER = com.st.nicobot.db.tables.Greeter.GREETER;

    /**
     * The table <code>PUBLIC.GOMMETTE</code>.
     */
    public static final Gommette GOMMETTE = com.st.nicobot.db.tables.Gommette.GOMMETTE;
}
